framework = "ARKit"
crate = "objc2-ar-kit"
required-crates = ["objc2", "objc2-foundation"]
maccatalyst = "14.0"
ios = "11.0"
visionos = "1.0"


class.ARQuickLookPreviewItem.skipped = true
class.ARReferenceImage.skipped = true
class.ARSCNView.skipped = true
protocol.ARSCNView.skipped = true
protocol.ARSCNViewDelegate.skipped = true
protocol.ARSKViewDelegate.skipped = true
class.ARSCNPlaneGeometry.skipped = true
class.ARSCNFaceGeometry.skipped = true
class.ARSKView.skipped = true
protocol.SCNDebugOptions.skipped = true
protocol.SCNSceneRenderer.skipped = true
typedef.ARSCNDebugOptions.skipped = true
static.ARSCNDebugOptionShowWorldOrigin.skipped = true
static.ARSCNDebugOptionShowFeaturePoints.skipped = true


# because of skipped dispatch_queue_t
class.ARSession.methods.delegateQueue.skipped = true
class.ARSession.methods."setDelegateQueue:".skipped = true

# becuase of skipped ARReferenceImage
class.ARGeoTrackingConfiguration.methods."setDetectionImages:".skipped = true
class.ARGeoTrackingConfiguration.methods.detectionImages.skipped = true
class.ARWorldTrackingConfiguration.methods.detectionImages.skipped = true
class.ARWorldTrackingConfiguration.methods."setDetectionImages:".skipped = true
class.ARImageTrackingConfiguration.methods.trackingImages.skipped = true
class.ARImageTrackingConfiguration.methods."setTrackingImages:".skipped = true
class.ARBodyTrackingConfiguration.methods."setDetectionImages:".skipped = true
class.ARBodyTrackingConfiguration.methods.detectionImages.skipped = true
class.ARImageAnchor.methods.referenceImage.skipped = true
